# This project has migrated to Observable Framework.
# See README.md for instructions on how to run and build the site.
# The original configuration is below:

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme